---
title: "PFAS_wrangle"
author: "Karly Nocera and Tay Holliday"
date: "4/17/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE}
# Set your working directory

getwd()

# Load your packages

library(tidyverse)
library(lubridate)

# Set your ggplot theme

mytheme <- theme_classic(base_size = 14) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)

# Load your datasets
PFAS_WWTP <- read.csv("../Data/Raw/2019_WWTP_orginal_asdataset.csv", stringsAsFactors = TRUE)

PFAS_Source <- read.csv("../Data/Raw/2018_PublicSupply_original.csv", stringsAsFactors = TRUE)

chainlength <- read.csv("../Data/Raw/chainlength.csv", stringsAsFactors = TRUE)

latlong <- read.csv("../Data/Raw/Locations_latlong.csv", stringsAsFactors = TRUE)


# PFAS_wwtp_wide_july <- read.csv("../Data/Processed/2019_WWTP_July.csv", stringsAsFactors = TRUE)
# PFAS_wwtp_wide_aug <- read.csv("../Data/Processed/2019_WWTP_Aug.csv", stringsAsFactors = TRUE)
# PFAS_wwtp_wide_sep <- read.csv("../Data/Processed/2019_WWTP_Sept.csv", stringsAsFactors = TRUE)
# 
# PFAS_source_wide <- read.csv("../Data/Processed/2018_PublicSupply_wide_latlong.csv", stringsAsFactors = TRUE)

```

# convert date format

```{r}

PFAS_WWTP$Sample.Date <- mdy(PFAS_WWTP$Sample.Date)
PFAS_Source$Sample.Date <- mdy(PFAS_Source$Sample.Date)

```


# delete unneeded source columns
```{r}

PFAS_Source <-
  PFAS_Source %>%
  select(Site, Sample.Date:lab.qual)

```


### WIDE

# create wide

```{r}

# drop lab qual

PFAS_WWTP_wide <-
  PFAS_WWTP %>%
  select(Site:ppt)


PFAS_Source_wide <-
  PFAS_Source %>%
  select(Site:ppt)

# pivot wider

PFAS_WWTP_wide <-
  PFAS_WWTP_wide %>%
  pivot_wider(names_from = Analyte, values_from = ppt)

PFAS_Source_wide <-
  PFAS_Source_wide %>%
  pivot_wider(names_from = Analyte, values_from = ppt)

```

# add total PFAS, sum PFOA/PFOS, short chain, long chain to wide

```{r}

PFAS_WWTP_wide <- 
  PFAS_WWTP_wide %>%
  rowwise() %>%
  mutate(TotalPFAS = sum(4.2, 6.2, 8.2, 10.2, N.EtFOSAA, N.MeFOSAA, Nafion.Byproduct.2, HFPO.DA, PFBA, PFBS, PFDA, PFDoA, PFDS, PFHpA, PFHpS, PFHxA, PFHxS, PFMOAA, PFMOBA, PFMOPrA, PFNA, PFNS, PFO2HxA, PFO3OA, PFO4DA, PFPeA, PFOA, PFOS, PFOSA, PFPeS, PFPrOPrA, PFTeA, PFTriA, PFUnA, PFHxDA, PFODA, ADONA, N.EtFOSA, Nafion.Byproduct.1, N.EtFOSE, N.MeFOSA, N.MeFOSE, PF3ONS, PF3OUdS, PFECA.G, na.rm=TRUE)) %>%
  mutate(SumPFOA.PFOS = sum(PFOA, PFOS, na.rm=TRUE)) %>%
  mutate(short.ppt = sum(PFBA, PFBS, PFHpA, PFHxA, PFPeS, PFPeA, 4.2, 6.2, na.rm = TRUE)) %>%
  mutate(long.ppt = sum(PFDS, PFDA, PFDoA, PFHpS, PFHxS, PFNS, PFNA, PFOSA, N.EtFOSAA, N.EtFOSA, N.MeFOSAA, N.MeFOSA, PFTeA, PFTriA, PFUnA, HFPO.DA, PFOA, PFOS, 8.2, 10.2, na.rm = TRUE))

```


### LONG

# chain lengths

```{r}

#Creates a function to determine if Analyte is short or long
chain.length.function <- function(x){
    ifelse(x %in% c("PFBA","PFBS","PFHpA","PFHxA","PFPeS","PFPeA","4.2", "6.2"), "short", "long")}

#Makes a chain.length column
PFAS_WWTP <- 
  PFAS_WWTP %>%
  mutate(chain.length = chain.length.function(Analyte)) 

PFAS_Source <- 
  PFAS_Source %>%
  mutate(chain.length = chain.length.function(Analyte)) 

```


# lat/long

```{r}

PFAS_WWTP <-
  left_join(PFAS_WWTP, latlong) %>%
  select(Site:chain.length,lat,long)

PFAS_Source <-
  left_join(PFAS_Source, latlong) %>%
  select(Site:chain.length,lat,long)

```


# save processed files

```{r}

# bound PFAS_wide

write.csv(PFAS_wide_clean, row.names=FALSE, file = "./Data/Processed/PFAS_wide_clean.csv")

# PFAS_clean(er)

write.csv(PFAS_long_clean, row.names=FALSE, file = "./Data/Processed/PFAS_long_clean.csv")

```

